#!/bin/sh
# Control line on ttyS1. The page sends one message per line:
#
#   attach <epoch>   a browser is here: set the clock, start the session
#   detach           (image build only) rewind to "waiting for a browser"
#   net up <way> <address/prefix> <gateway> <dns> <mtu>
#                    a way out is up (src/net/): put eth0 on it
#   net down <why>   it went down, or was turned off: take eth0 off again
#   net known        this browser already has a WARP device …
#   net forgotten    … or no longer
#
# Window sizes need no message: the virtio console reports them itself.

stty -echo
echo ready

while read -r cmd arg; do
	case $cmd in
	attach)
		date -s "@$arg" > /dev/null
		touch /run/attached
		;;
	detach)
		rm -f /run/attached
		echo detached
		;;
	net)
		set -- $arg
		case $1 in
		up)
			ip link set eth0 mtu "$6" up
			ip addr flush dev eth0
			ip addr add "$3" dev eth0
			ip route add "$4" dev eth0 2> /dev/null # on-link already, unless /32
			ip route add default via "$4"
			echo "nameserver $5" > /etc/resolv.conf
			echo "up $2 ${3%/*}" > /run/net/state
			;;
		down)
			ip addr flush dev eth0
			ip link set eth0 down
			shift
			echo "down $*" > /run/net/state
			;;
		known) touch /run/net/known ;;
		forgotten) rm -f /run/net/known ;;
		esac
		;;
	esac
done
